# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NOT_STARTED_YET', 'not_started_yet'), ('ON_GOING', 'on_going'), ('JUST_STARTED', 'just_started'), ('ENDED', 'ended'), ('LESS_THAN_WEEK', 'less_than_week')], default='NOT_STARTED_YET', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
